apiVersion: v2
name: cloud-efficiency-engine
description: Kubernetes-native FinOps and cloud cost optimization engine
type: application
version: 0.4.0
appVersion: "0.4.0"
keywords:
  - finops
  - kubernetes
  - cloud-cost
  - optimization
  - prometheus
  - grafana
home: https://github.com/Pablo-Loyola-Tantaruna/cloud-efficiency-engine
sources:
  - https://github.com/Pablo-Loyola-Tantaruna/cloud-efficiency-engine
maintainers:
  - name: Pablo Loyola Tantaruna