apiVersion: v1
kind: Service
metadata:
  name: cloud-efficiency-engine
  namespace: cloud-efficiency-engine
  labels:
    app: cloud-efficiency-engine
    monitoring: enabled
spec:
  selector:
    app: cloud-efficiency-engine
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP