apiVersion: apps/v1
kind: Deployment

metadata:
  name: payments-api
  namespace: cloud-efficiency-engine

  labels:
    app: payments-api
    app.kubernetes.io/part-of: cloud-efficiency-engine-demo

spec:

  replicas: 3

  selector:
    matchLabels:
      app: payments-api

  template:

    metadata:
      labels:
        app: payments-api

    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        seccompProfile:
          type: RuntimeDefault

      containers:

        - name: payments-api

          image: nginxinc/nginx-unprivileged:1.27-alpine
          imagePullPolicy: IfNotPresent

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          resources:

            requests:
              cpu: "1000m"
              memory: "1Gi"

            limits:
              cpu: "2000m"
              memory: "2Gi"

          ports:
            - containerPort: 8080

          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: cache
              mountPath: /var/cache/nginx

      volumes:
        - name: tmp
          emptyDir: {}
        - name: cache
          emptyDir: {}

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: orders-api
  namespace: cloud-efficiency-engine

  labels:
    app: orders-api
    app.kubernetes.io/part-of: cloud-efficiency-engine-demo

spec:

  replicas: 2

  selector:
    matchLabels:
      app: orders-api

  template:

    metadata:
      labels:
        app: orders-api

    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        seccompProfile:
          type: RuntimeDefault

      containers:

        - name: orders-api

          image: nginxinc/nginx-unprivileged:1.27-alpine
          imagePullPolicy: IfNotPresent

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          resources:

            requests:
              cpu: "500m"
              memory: "1Gi"

            limits:
              cpu: "1000m"
              memory: "2Gi"

          ports:
            - containerPort: 8080

          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: cache
              mountPath: /var/cache/nginx

      volumes:
        - name: tmp
          emptyDir: {}
        - name: cache
          emptyDir: {}
